In [ ]:
import numpy

In [2]:
n=numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [6]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
import cv2


In [11]:
im_g=cv2.imread("smallgray.png",2)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [12]:
cv2.imwrite("newimage.png",im_g)

True

In [14]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [16]:
ims=numpy.hstack((im_g,im_g))
#same you can do with .vstack
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [17]:
cv2.imwrite("stack.png",ims)

True

In [24]:
lst=numpy.vsplit(ims,3)
lst


[array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147, 198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)]